"""empty message

Revision ID: 15001e2db881
Revises: 6f27c7ee5782
Create Date: 2023-11-01 16:05:26.394622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15001e2db881'
down_revision = '6f27c7ee5782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_column('branch_name')

    # ### end Alembic commands ###
